[project]
name = "sg-com-serv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymarkdownlnt>=0.9.35",
    "typer>=0.24.1",
]
