filenames:
  - /var/log/auth.log
  - /var/log/syslog
labels:
  type: syslog
---
filenames:
  - /caddy/*.log
labels:
  type: caddy
---
filenames:
  - /var/log/teamspeak/*.log
labels:
  type: teamspeak
